version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'cron'
      # Every other Sunday at 07:00.
      cronjob: '0 7 * * sun%2'
      timezone: 'Asia/Jerusalem'
    commit-message:
      prefix: 'chore'

    # Should match pnpm's `minimumReleaseAge`
    cooldown:
      default-days: 1 # zizmor: ignore[dependabot-cooldown] We're fine with 1 day.

    groups:
      # Matching the pnpm catalog entries manually since Dependabot matches them under the production group.
      # See: https://github.com/dependabot/dependabot-core/issues/14824
      #
      # Note: Excluding eslint-related packages since they have their own group.
      pnpm-catalog:
        patterns:
          - '@arethetypeswrong/cli'
          - '@typescript/native-preview'
          - '@vitest/coverage-v8'
          - 'publint'
          - 'tsdown'
          - 'typescript'
          - 'vitest'

      # All eslint-related packages are better to be updated together.
      eslint:
        patterns:
          - '*eslint*'
          - 'globals'

      npm-development:
        dependency-type: 'development'
        patterns:
          - '**'

      npm-production:
        dependency-type: 'production'
        patterns:
          - '**'

  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      - '/.github/actions/*'

    cooldown:
      default-days: 1 # zizmor: ignore[dependabot-cooldown] We're fine with 1 day.

    schedule:
      interval: 'cron'
      # Every other Sunday at 07:00.
      cronjob: '0 7 * * sun%2'
      timezone: 'Asia/Jerusalem'
    commit-message:
      prefix: 'ci'
    groups:
      github-actions:
        group-by: dependency-name
