name: 'Prepare: Install'
description: 'Prepares the repo by installing dependencies'
inputs:
  cache-name:
    description: 'The name of the cache to restore, if needed'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'pnpm'

    - name: Install Dependencies
      shell: bash
      run: pnpm i

    - name: Restore Turbo Cache
      uses: actions/cache@v4
      if: inputs.cache-name != ''
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ inputs.cache-name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ inputs.cache-name }}-
