name: Check Major Version
description: |
  Check whether the changeset contains a major version bump

  NOTE: This action requires dependencies to be installed and `fetch-depth: 0` in `actions/checkout` to work,
        and should only be used in pull requests.

outputs:
  has-major:
    description: Whether the changeset contains a major version bump ('true' or 'false')
    value: ${{ steps.check.outputs.has-major }}

runs:
  using: composite
  steps:
    - name: Check for Major Changeset
      id: check
      shell: bash
      env:
        BASE_REF: ${{ github.event.pull_request.base.ref }}
      run: |
        OUTPUT_FILE=./.changeset-status.json

        pnpm changeset status --since "origin/$BASE_REF" --output="$OUTPUT_FILE" &> /dev/null || true

        node .github/scripts/check-major-version.ts "$OUTPUT_FILE"
