name: Dependabot Changeset

on: pull_request

permissions: {}

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  generate:
    name: Generate
    # if: |
    #   github.event.pull_request.user.login == 'dependabot[bot]' &&
    #   startsWith(github.head_ref, 'dependabot/npm_and_yarn/npm-production-')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code # zizmor: ignore[artipacked] Need persisted token to commit the changeset.
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install Dependencies
        uses: ./.github/actions/install

      - name: Configure git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Generate changeset
        run: |
          touch a.txt
          git add a.txt
          git commit -m "chore: add a.txt"
          git push
