name: Figma Code Connect Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    name: Publish
    if: github.repository_owner == 'drivenets'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    concurrency:
      group: figma-code-connect @ main
      cancel-in-progress: false

    steps:
      - name: Checkout source code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install Dependencies
        uses: ./.github/actions/install

      - name: Cache turbo
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-figma-publish-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-figma-publish-

      - name: Publish Code Connect files
        run: pnpm figma:publish
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
