name: PR Name Linter
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

permissions: {}

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    # Skip release & dependabot PRs
    if: |
      ! (github.event.pull_request.title == 'chore(release): publish' && github.event.pull_request.user.login == 'github-actions[bot]') &&
      ! (github.event.pull_request.user.login == 'dependabot[bot]')

    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Dependencies
        uses: ./.github/actions/install

      - name: Check for breaking changes
        id: check-major
        uses: ./.github/actions/check-major-version

      - name: Run PR name linter
        env:
          TITLE: ${{ github.event.pull_request.title }}
          HAS_BREAKING_CHANGES: ${{ steps.check-major.outputs.has-major }}
        run: echo "$TITLE" | npx commitlint
