name: Sync next branch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: next
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          persist-credentials: false

      - name: Setup Git User
        uses: ./.github/actions/setup-git-user

      - name: Rebase onto main
        run: git rebase origin/main

      - name: Force push
        run: git push --force-with-lease
