name: Sync next branch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: next
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          persist-credentials: false

      - name: Setup Git User
        uses: ./.github/actions/setup-git-user

      - name: Rebase onto main
        run: git rebase origin/main

      - name: Force push
        run: git push --force-with-lease
